version: "3.9"
services:
    reverseproxy:
        depends_on: 
            - python
        image: reverseproxy
        build: .
        ports:
            - 8080:8080
        restart: always
    python:
        depends_on: 
            - redis
        build: ./python

    redis:
        image: "redis:alpine"


# services:

 
#     # nginx:
#     #     depends_on:
#     #         - reverseproxy
#     #     image: nginx:alpine
#     #     restart: always
 
#     # apache:
#     #     depends_on:
#     #         - reverseproxy
#     #     image: httpd:alpine
#     #     restart: always
